name: Docker Build and Push to ACR for PHP App

on:
  push:
    branches:
      - main  # Trigger on the main branch

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Specify the PHP version you need

      # Install dependencies (if using Composer)
      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-progress --no-suggest

      # Run tests (if you have any)
      - name: Run tests for PHP
        run: |
          vendor/bin/phpunit

      - name: Docker Login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          IMAGE_NAME=${{ secrets.ACR_NAME }}.azurecr.io/myphpapp
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

      - name: Push Docker Image to ACR
        run: |
          IMAGE_NAME=${{ secrets.ACR_NAME }}.azurecr.io/myphpapp
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest

      - name: Logout from Docker
        run: docker logout

  # Optional: Deploy to AKS using Helm
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group RGroup --name RGroup-aks

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy PHP app to AKS
        run: |
          helm upgrade --install sample-php ./helm-charts \
            --set image.repository=${{ secrets.ACR_NAME }}.azurecr.io/myphpapp \
            --set image.tag=latest
